services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: python
    volumes:
    # script
      - ./script.py:/script.py
    # data
      - ./data:/data
    command: python script.py
      